site_name: Document Storage
nav:
  - Home: 'index.md'
  - Summary: 'summary.md'
  - Readme: 'readme.md'
  - Architecture: 'architecture.md'
plugins:
  - techdocs-core
  - kroki:
      FencePrefix: ''
